mysql:
  host: localhost
  port: 3306
  username: root
  password: root123

redis:
  host: localhost
  port: 6379
  database: 0


spring:
  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}

  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        reset-enable: true
        url-pattern: /druid/*
        allow:
        deny:
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        profile-enable: true
        session-stat-enable: false

    dynamic:
      # 全局配置，数据源可覆盖
      druid:
        initial-size: 1 # 初始连接数
        max-active: 3 # 最大连接池数量
        min-idle: 1 # 最小连接池数量
        max-wait: 60000
        pool-prepared-statements: false
        validation-query: "SELECT 1"
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 3000
        min-evictable-idle-time-millis: 300000
        # Filter
        # wall不兼容phoenix
        filters: stat
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true

      primary: master
      datasource:
        master:
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql.host}:${mysql.port}/master_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

#        slave_1:
#          username: ${mysql.username}
#          password: ${mysql.password}
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://${mysql.host}:${mysql.port}/slave_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8


mybatis-plus:
  # classpath要加上后面的*，表示通配符，匹配任意路径
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.flyingglass.mybatisplus.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true # 开启xml缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    interceptors:

  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
